/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.Programacion1.Tarea4;

import Formularios.Login;

public class App {
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }
}
