/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;
import Controlador.controladorLogin;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author ramir
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());
    
    
    private final controladorLogin controlador;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        
        configurarPlaceholders();
        configurarIconoVentana();
        controlador = new controladorLogin();


    }
    
        /**
     * Configura el icono personalizado que se muestra en la barra de título.
     */
    private void configurarIconoVentana() {
        Image icon = Toolkit.getDefaultToolkit()
                .getImage(getClass().getResource("/login-usuarios.png"));
        setIconImage(icon);
    }
    
    private void configurarPlaceholders() {
        aplicarPlaceholder(txtNombreUsuario, "Ingrese su nombre de usuario aquí");
        aplicarPlaceholder(txtContraseña, "Ingrese su contraseña aquí");
    }

/**
     * Configura un texto de placeholder en un JTextField.
     *
     * @param textField  campo de texto a configurar
     * @param placeholder texto que se mostrará como marcador
     */
    private void aplicarPlaceholder(JTextField textField, String placeholder) {
        textField.setText(placeholder);
        textField.setForeground(new Color(150, 150, 150));

        textField.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (textField.getText().equals(placeholder)) {
                    textField.setText("");
                    textField.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (textField.getText().isEmpty()) {
                    textField.setText(placeholder);
                    textField.setForeground(new Color(150, 150, 150));
                }
            }
        });
    }

    // Devuelve el contenido de un JTextField, sustituyendo el placeholder por cadena vacía
    private String obtenerTextoSinPlaceholder(JTextField textField, String placeholder) {
        String text = textField.getText();
        return text.equals(placeholder) ? "" : text;
    }

    // Devuelve el contenido de un JPasswordField, sustituyendo el placeholder por cadena vacía
    private String obtenerTextoSinPlaceholder(JPasswordField passwordField, String placeholder) {
        String text = new String(passwordField.getPassword());
        return text.equals(placeholder) ? "" : text;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panelfondo = new javax.swing.JPanel();
        PanelBanner = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        btnIniciarSesión = new javax.swing.JButton();
        lblRegistrar = new javax.swing.JLabel();
        btnRegistrarse = new javax.swing.JButton();
        txtContraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(getIconImages());
        setResizable(false);

        Panelfondo.setBackground(new java.awt.Color(255, 255, 255));

        PanelBanner.setBackground(new java.awt.Color(251, 54, 64));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Iniciar Sesión");

        javax.swing.GroupLayout PanelBannerLayout = new javax.swing.GroupLayout(PanelBanner);
        PanelBanner.setLayout(PanelBannerLayout);
        PanelBannerLayout.setHorizontalGroup(
            PanelBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBannerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        PanelBannerLayout.setVerticalGroup(
            PanelBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBannerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblNombreUsuario.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        lblNombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreUsuario.setText("Nombre de usuario:");

        txtNombreUsuario.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N

        lblContraseña.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        lblContraseña.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblContraseña.setText("Contraseña:");

        btnIniciarSesión.setBackground(new java.awt.Color(234, 231, 231));
        btnIniciarSesión.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        btnIniciarSesión.setText("Iniciar sesión");
        btnIniciarSesión.addActionListener(this::btnIniciarSesiónActionPerformed);

        lblRegistrar.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        lblRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistrar.setText("¿Aún no te has registrado? ¡Registrate aquí!");

        btnRegistrarse.setBackground(new java.awt.Color(234, 231, 231));
        btnRegistrarse.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.addActionListener(this::btnRegistrarseActionPerformed);

        txtContraseña.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        txtContraseña.setText("jPasswordField1");
        txtContraseña.addActionListener(this::txtContraseñaActionPerformed);

        javax.swing.GroupLayout PanelfondoLayout = new javax.swing.GroupLayout(Panelfondo);
        Panelfondo.setLayout(PanelfondoLayout);
        PanelfondoLayout.setHorizontalGroup(
            PanelfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelfondoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PanelfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelfondoLayout.createSequentialGroup()
                        .addComponent(lblContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PanelfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelfondoLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btnIniciarSesión))
                            .addGroup(PanelfondoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelfondoLayout.createSequentialGroup()
                        .addComponent(lblNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelfondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelfondoLayout.createSequentialGroup()
                        .addComponent(lblRegistrar)
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelfondoLayout.createSequentialGroup()
                        .addComponent(btnRegistrarse)
                        .addGap(181, 181, 181))))
        );
        PanelfondoLayout.setVerticalGroup(
            PanelfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelfondoLayout.createSequentialGroup()
                .addComponent(PanelBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(PanelfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(PanelfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(txtContraseña))
                .addGap(39, 39, 39)
                .addComponent(btnIniciarSesión)
                .addGap(18, 18, 18)
                .addComponent(lblRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarse)
                .addGap(0, 80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panelfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panelfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnIniciarSesiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesiónActionPerformed
        String username = obtenerTextoSinPlaceholder(txtNombreUsuario, "Ingrese su nombre de usuario aquí");
        String password = obtenerTextoSinPlaceholder(txtContraseña, "Ingrese su contraseña aquí");

        boolean autenticado = controlador.iniciarSesion(username, password);

        if (autenticado) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Inicio de sesión exitoso.",
                    "Información",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
            );

            Usuarios vistaUsuarios = new Usuarios();
            vistaUsuarios.setVisible(true);
            vistaUsuarios.setLocationRelativeTo(null);

            dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Credenciales inválidas o datos incompletos.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnIniciarSesiónActionPerformed

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        // Crear el formulario Registrar
        Registrar ventanaRegistro = new Registrar();
        ventanaRegistro.setVisible(true);
        ventanaRegistro.setLocationRelativeTo(null); // Centrar ventana

        // Cerrar ventana de Login
        this.dispose();
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info :
                    javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBanner;
    private javax.swing.JPanel Panelfondo;
    private javax.swing.JButton btnIniciarSesión;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblRegistrar;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
