/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Controlador.controladorUsuarios;
import PersonaYUsuario.Usuario;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ramir
 */
public class Usuarios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Usuarios.class.getName());
    private final controladorUsuarios controlador = new controladorUsuarios();


    /**
     * Creates new form Usuarios
     */
    public Usuarios() {
        initComponents();
        configurarTabla();
        cargarUsuariosEnTabla();
        configurarIconoVentana();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBanner = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRegistrarse3 = new javax.swing.JButton();
        PanelFondo = new javax.swing.JPanel();
        PanelBanner5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaRegistros = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        PanelBanner.setBackground(new java.awt.Color(251, 54, 64));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Actualizar usuario");

        javax.swing.GroupLayout PanelBannerLayout = new javax.swing.GroupLayout(PanelBanner);
        PanelBanner.setLayout(PanelBannerLayout);
        PanelBannerLayout.setHorizontalGroup(
            PanelBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelBannerLayout.setVerticalGroup(
            PanelBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBannerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        btnRegistrarse3.setBackground(new java.awt.Color(234, 231, 231));
        btnRegistrarse3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        btnRegistrarse3.setText("Eliminar usuario");
        btnRegistrarse3.addActionListener(this::btnRegistrarse3ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelFondo.setBackground(new java.awt.Color(255, 255, 255));

        PanelBanner5.setBackground(new java.awt.Color(251, 54, 64));

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Gestión de usuarios");

        javax.swing.GroupLayout PanelBanner5Layout = new javax.swing.GroupLayout(PanelBanner5);
        PanelBanner5.setLayout(PanelBanner5Layout);
        PanelBanner5Layout.setHorizontalGroup(
            PanelBanner5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
        );
        PanelBanner5Layout.setVerticalGroup(
            PanelBanner5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBanner5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        TablaRegistros.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        TablaRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Correo", "Teléfono", "Usuario"
            }
        ));
        jScrollPane1.setViewportView(TablaRegistros);

        btnEliminar.setBackground(new java.awt.Color(234, 231, 231));
        btnEliminar.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        btnEliminar.setText("Eliminar usuario");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnCrear.setBackground(new java.awt.Color(234, 231, 231));
        btnCrear.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        btnCrear.setText("Crear usuario");
        btnCrear.addActionListener(this::btnCrearActionPerformed);

        btnActualizar.setBackground(new java.awt.Color(234, 231, 231));
        btnActualizar.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        btnActualizar.setText("Actualizar usuario");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnCerrar.setBackground(new java.awt.Color(234, 231, 231));
        btnCerrar.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        btnCerrar.setText("Cerrar sesión");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        javax.swing.GroupLayout PanelFondoLayout = new javax.swing.GroupLayout(PanelFondo);
        PanelFondo.setLayout(PanelFondoLayout);
        PanelFondoLayout.setHorizontalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBanner5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFondoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(17, 17, 17))
                    .addGroup(PanelFondoLayout.createSequentialGroup()
                        .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelFondoLayout.createSequentialGroup()
                                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PanelFondoLayout.setVerticalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addComponent(PanelBanner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar)
                    .addComponent(btnCrear))
                .addGap(18, 18, 18)
                .addComponent(btnCerrar)
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
              int fila = TablaRegistros.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this,
                    "Seleccione un usuario para eliminar.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String username = TablaRegistros.getValueAt(fila, 4).toString();

        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que desea eliminar el usuario \"" + username + "\"?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            boolean ok = controlador.eliminarUsuario(username);
            if (ok) {
                JOptionPane.showMessageDialog(this,
                        "Usuario eliminado correctamente.",
                        "Información",
                        JOptionPane.INFORMATION_MESSAGE);
                cargarUsuariosEnTabla();
            } else {
                JOptionPane.showMessageDialog(this,
                        "No se pudo eliminar el usuario.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            logger.log(Level.SEVERE, "Error al eliminar usuario", ex);
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
               // Solicitar los datos mediante diálogos simples.
        String nombre = JOptionPane.showInputDialog(this, "Nombre:");
        if (nombre == null || nombre.isBlank()) return;

        String apellido = JOptionPane.showInputDialog(this, "Apellido:");
        if (apellido == null || apellido.isBlank()) return;

        String correo = JOptionPane.showInputDialog(this, "Correo:");
        if (correo == null || correo.isBlank()) return;

        String telefono = JOptionPane.showInputDialog(this, "Teléfono:");
        if (telefono == null || telefono.isBlank()) return;

        String nombreUsuario = JOptionPane.showInputDialog(this, "Nombre de usuario:");
        if (nombreUsuario == null || nombreUsuario.isBlank()) return;

        String clave = JOptionPane.showInputDialog(this, "Contraseña:");
        if (clave == null || clave.isBlank()) return;

        String confirmar = JOptionPane.showInputDialog(this, "Confirmar contraseña:");
        if (confirmar == null || confirmar.isBlank()) return;

        try {
            boolean ok = controlador.crearUsuario(
                    nombre,
                    apellido,
                    correo,
                    telefono,
                    nombreUsuario,
                    clave,
                    confirmar
            );

            if (ok) {
                JOptionPane.showMessageDialog(this,
                        "Usuario registrado correctamente.",
                        "Información",
                        JOptionPane.INFORMATION_MESSAGE);
                cargarUsuariosEnTabla();
            } else {
                JOptionPane.showMessageDialog(this,
                        "No se pudo completar el registro. Verifique los datos.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            logger.log(Level.SEVERE, "Error al registrar usuario", ex);
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
                int fila = TablaRegistros.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this,
                    "Seleccione un usuario para actualizar.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Usuario original (para localizar el registro en BD)
        String usernameOriginal = TablaRegistros.getValueAt(fila, 4).toString();

        try {
            Usuario actual = controlador.obtenerUsuario(usernameOriginal);
            if (actual == null) {
                JOptionPane.showMessageDialog(this,
                        "El usuario seleccionado ya no existe.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                cargarUsuariosEnTabla();
                return;
            }

            // Se muestran los valores actuales como propuesta
            String nombre = JOptionPane.showInputDialog(this, "Nombre:", actual.getNombre());
            if (nombre == null || nombre.isBlank()) return;

            String apellido = JOptionPane.showInputDialog(this, "Apellido:", actual.getApellido());
            if (apellido == null || apellido.isBlank()) return;

            String correo = JOptionPane.showInputDialog(this, "Correo:", actual.getCorreo());
            if (correo == null || correo.isBlank()) return;

            String telefono = JOptionPane.showInputDialog(this, "Teléfono:", actual.getTelefono());
            if (telefono == null || telefono.isBlank()) return;

            String nombreUsuario = JOptionPane.showInputDialog(this, "Nombre de usuario:", actual.getNombreUsuario());
            if (nombreUsuario == null || nombreUsuario.isBlank()) return;

            String nuevaClave = JOptionPane.showInputDialog(this,
                    "Nueva contraseña (dejar vacío para mantener la actual):");

            // Construimos un objeto Usuario con los datos modificados
            Usuario modific = new Usuario(
                    nombre,
                    apellido,
                    correo,
                    telefono,
                    nombreUsuario,
                    (nuevaClave == null || nuevaClave.isBlank())
                            ? actual.getClaveAcceso()
                            : nuevaClave
            );

            boolean ok = controlador.actualizarUsuario(usernameOriginal, modific);

            if (ok) {
                JOptionPane.showMessageDialog(this,
                        "Usuario actualizado correctamente.",
                        "Información",
                        JOptionPane.INFORMATION_MESSAGE);
                cargarUsuariosEnTabla();
            } else {
                JOptionPane.showMessageDialog(this,
                        "No se pudo actualizar el usuario.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception ex) {
            logger.log(Level.SEVERE, "Error al actualizar usuario", ex);
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnRegistrarse3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarse3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarse3ActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        Login login = new Login();
        login.setLocationRelativeTo(this);
        login.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void configurarIconoVentana() {
        try {
            Image icono = Toolkit.getDefaultToolkit()
                    .getImage(getClass().getResource("/login-usuarios.png"));
            setIconImage(icono);
        } catch (Exception e) {
            // Si el recurso no existe, simplemente se omite sin interrumpir la aplicación.
            logger.log(Level.WARNING, "No se pudo cargar el icono de la ventana.", e);
        }
    }
    
     private void configurarTabla() {
        TablaRegistros.setRowHeight(26);
        TablaRegistros.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        TablaRegistros.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        TablaRegistros.setShowGrid(false);
        TablaRegistros.setIntercellSpacing(new Dimension(0, 0));

        TablaRegistros.getTableHeader().setBackground(new Color(48, 63, 159));
        TablaRegistros.getTableHeader().setForeground(Color.WHITE);

        // Las celdas no se editan directamente desde la tabla
        TablaRegistros.setDefaultEditor(Object.class, null);

        // Estilo de filas alternadas y selección
        TablaRegistros.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(
                    JTable table, Object value, boolean isSelected,
                    boolean hasFocus, int row, int column) {

                Component c = super.getTableCellRendererComponent(
                        table, value, isSelected, hasFocus, row, column);

                if (!isSelected) {
                    c.setBackground(row % 2 == 0
                            ? new Color(245, 245, 245)
                            : Color.WHITE);
                    c.setForeground(Color.BLACK);
                } else {
                    c.setBackground(new Color(66, 133, 244));
                    c.setForeground(Color.WHITE);
                }

                return c;
            }
        });
    }
     
    
    /** Recupera los usuarios desde la capa de negocio y los muestra en la tabla. */
    private void cargarUsuariosEnTabla() {
        try {
            DefaultTableModel modelo = (DefaultTableModel) TablaRegistros.getModel();
            modelo.setRowCount(0); // limpia filas

            List<Usuario> usuarios = controlador.obtenerTodos();
            for (Usuario u : usuarios) {
                Object[] fila = {
                    u.getNombre(),
                    u.getApellido(),
                    u.getCorreo(),
                    u.getTelefono(),
                    u.getNombreUsuario()
                };
                modelo.addRow(fila);
            }
        } catch (Exception ex) {
            logger.log(Level.SEVERE, "Error al cargar usuarios", ex);
            JOptionPane.showMessageDialog(
                    this,
                    "No se pudieron cargar los usuarios.\nDetalle: " + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
    








    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Usuarios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBanner;
    private javax.swing.JPanel PanelBanner1;
    private javax.swing.JPanel PanelBanner2;
    private javax.swing.JPanel PanelBanner3;
    private javax.swing.JPanel PanelBanner4;
    private javax.swing.JPanel PanelBanner5;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JTable TablaRegistros;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrarse3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
